### ISSUE TITLE
Authentication with Ap EasyPower Login Data fail

### ISSUE THREAD

**Issue by schumaennle** [n0liver/HAAC#3]
Tried to use my AP EasyPower App login data, but authentification failed. Is this client usable for the EZ1-M inverter?

**Comment by n0liver** [comment]
Hi,
this integration uses the APS EMA app API to query solar panel data, I guess the AP EasyPower app uses different authentication and possibly different API endpoints. Since this integration doesn't communicate with inverters directly and only with APS servers I would assume it's inverter-agnostic and should work with any inverter that APS supports.

**Comment by hjt987** [comment]
Hi, I am normally using the AP Easy Power Ampp and with the same username / password where I can there successfully connect to the cloud to read all the EZ1M data, I have no success with your integration. I get stuck with the login and it tells me 'could not authenticate'.  Is there a way to make this work? If not can I just use the EZ1M with the other apps like APS EMA as mentioned above?

**Comment by n0liver** [comment]
Hi,
I have zero knowledge about this Easy Power App. Like mentioned, this integration uses the same authentication and API endpoints that the APS EMA app uses. This means that this integration could work for you as long as you are able to see solar panel data in the APS EMA app. If EZ1M is not supported by the APS EMA app, I'm afraid this integration won't work for you..
